"use strict";
const myEx = require("express");
const ejs = require("ejs");
const logger = require("morgan");
const bodyparser = require("body-parser");
const favicon = require("serve-favicon");
const mysession = require("express-session");
const cookieParser = require("cookie-parser");
const userRouter = require("./router/userRouter");
const staffRouter = require("./router/staffRouter");
const db = require("./model/sqlpool");
const app = myEx();